stages:
  - build_back
  - deploy

build_back:
  stage: build_back
  before_script:
    - docker-compose stop
  script:
    - |
      export PATH="/root/.sdkman/candidates/java/current/bin:$PATH"
      echo $PATH
      pwd
      cd backend
      ./gradlew -Dorg.gradle.jvmargs=-Xmx512m build
#  after_script:
#    - |
#      docker-compose start
#      while ! docker logs backend --tail=1 | grep -w "Started SpiApplication";
#      do
#      sleep 10
#      echo "Waiting for backend to load ..."
#      done
  artifacts:
    expire_in: 30 mins
    paths:
      - backend/build/libs/spi.jar

deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up --build -d
    - docker image prune -a -f
  only:
    - main