version: '3.5'
services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spi-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-password}
      POSTGRES_USER: admin
      POSTGRES_DB: spi

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-local-compose}
        POSTGRES_PASS: ${POSTGRES_PASS:-password}
    ports:
      - "9000:9000"
    networks:
      - spi-network
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - './frontend:/usr/src/app'
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - spi-network
    depends_on:
      - backend

networks:
  spi-network:
    driver: bridge

volumes:
  pgdata:

