server:
  port: 9000

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: ccfit.nsu.ru.spi.configs.PhysicalNamingStrategyImpl
    properties:
      hibernate:
        query:
          plan_cache_max_size: 256
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost/spi
    username: admin
    password: 12345678

logging:
  level:
    org:
      springframework:
        security: INFO
        web: INFO

springdoc:
  api-docs:
    path: /api/documentation/v3/api-docs
  swagger-ui:
    path: /api/documentation/swagger-ui.html

app:
  security:
    jwt:
      secret: spi_secret
      expirationMs: 1800000000